# Classification
# Keywords synced from C:/Users/user/Downloads/keywords_all.xlsx

KEYWORDS = {
    '개정/변경': [
        'revision',
        'revised',
        '개정',
        'update',
        'upated',
        '업데이트',
        'amendment',
        'amended',
        'corrigendum',
        'errata',
        '정정',
        '수정',
        'draft',
        'consultation',
        'public comment',
        'concept paper',
        '초안',
        'effective date',
        'implementation date',
        'transition period',
        '시행',
        '시행일',
    ],
    '무균/주사제': [
        'aseptic',
        'sterile',
        'sterilization',
        'aseptic processing',
        '무균',
        '무균 공정',
        '멸균',
        'CCS',
        'contamination control strategy',
        '오염 관리 전략',
        'cleanroom',
        'HVAC',
        'HEPA',
        'airflow',
        'smoke study',
        '청정작업실',
        '청정실',
        '공기 조화 장치',
        '헤파',
        '기류',
        '기류패턴 테스트',
        'EM',
        'environmental monitoring',
        'trending',
        'alert level',
        'action level',
        '환경모니터링',
        '경고수준',
        '조치수준',
        'APS',
        'media fill',
        'worst case',
        'intervention',
        '무균공정모의시험',
        '배지충전시험',
        '메디아필',
        '간섭',
        '최악의 경우',
        'sterilizing filter',
        'integrity test',
        'PUPSIT',
        '멸균 필터',
        '필터 완전성 시험',
        'endotoxin',
        'pyrogen',
        'bioburden',
        '엔도톡신',
        '발열성물질',
        '바이오버든',
        'CCI',
        'container closure integrity',
        'leak test',
        '용기 완전성 시험',
        '용기 마개 완전성 시험',
        'particulates',
        'visible particles',
        'settle plate',
        'contact plate',
        'air sample',
        '부유입자',
        '부유균',
        '낙하균',
        '표면균',
        '미생물',
        '미립자',
    ],
    '품질 시스템(QMS)': [
        'deviation',
        'investigation',
        'root cause',
        'CAPA',
        'effectiveness check',
        '일탈',
        '조사',
        '근본 원인',
        '유효성 평가',
        '시정 조치',
        '예방 조치',
        'changecontrol',
        'change menagement',
        'impact assessment',
        '변경',
        '변경관리',
        '영향평가',
        '영향성 평가',
        'risk assessment',
        'QRM',
        'FMEA',
        '위험 관리',
        '품질 위험 관리',
        '위험 평가',
        'stability',
        'OOS',
        'OOT',
        'data trending',
        '안정성',
        '규격 초과',
        '경향 초과',
    ],
    'Validation': [
        'qualification',
        'DQ',
        'IQ',
        'OQ',
        'PQ',
        'Process validation',
        'continued process verification',
        'Shipping validation',
        '적격성 평가',
        '검증',
        '검정',
        '밸리데이션',
        '공정 밸리데이션',
        '지속적 공정 검증',
        '운송 밸리데이션',
    ],
    'Data integrity': [
        'Data integrity',
        'ALCOA',
        'ALCOA+',
        'audit trail',
        'electronic records',
        'Raw data',
        '데이터 완전성',
        '점검 기록',
        '전자 기록',
        '원 기록',
        '원천 기록',
        'Part 11',
        'computerized system validation',
        'CSV',
        '컴퓨터화 시스템',
        '컴퓨터 시스템 밸리데이션',
        'access control',
        'privilege',
        'backup',
        'disaster recovery',
        'security',
        'log review',
        '접근 권한',
        '백업',
        '재난 복구',
    ],
    '약전': [
        'monograph',
        'general chapter',
        'general notice',
        '각조',
        '개별 기준',
        '일반 시험법',
        '일반 기준',
        '총칙',
        '일반 총칙',
        'revision bulletin',
        'official text',
        'harmonization',
        '개정 공지',
        '개정 고시',
        '공식 문서',
        '공식 본문',
        '조화',
        '국제 조화',
        'method validation',
        'verification',
        'specificity',
        'accuracy',
        'precision',
        'robustness',
        '시험법 밸리데이션',
        '시험법 검증',
        '시험법 적합성 확인',
        '검증',
        '특이성',
        '정확성',
        '정밀성',
        '강건성',
        '견고성',
        'impurities',
        'residual solvents',
        'elemental impurities',
        '불순물',
        '순도 시험',
        '잔류용매',
        '잔류용매 시험',
        'dissolution',
        'assay',
        'related substances',
        'sterility test',
        'endotoxin test',
        '용출',
        '용출 시험',
        '정량',
        '함량 시험',
        '함량',
        '유연물질',
        '유연물질 시험',
        '무균 시험',
        '엔도톡신',
    ],
    '고형제 - 칭량': [
        'dispensing',
        'weighing',
        'material handling',
        '칭량',
        'blend',
        'blending',
        'mixing',
        'blend uniformity',
        'content uniformity',
        '혼합',
        '혼합물',
        '혼합 균일성',
        '함량 균일성',
        'segregation',
        'demixing',
        'particle size distribution',
        '분리',
        '성분 분리',
        '탈혼합',
        '입도 분포',
        '입자 크기 분포',
        'flowability',
        'bulk density',
        'tapped density',
        '유동성',
        '겉보기 밀도',
        '다짐 밀도',
    ],
    '고형제 - 과립 & 건조': [
        'wet granulation',
        'dry granulation',
        'roller compaction',
        '과립',
        '습식 과립',
        '건식 과립',
        'fluid bed granulation',
        'high shear granulation',
        '유동층 과립',
        '고전단 과립',
        'drying',
        'LOD',
        'moisture content',
        '건조',
        '건조 감량',
        '수분 함량',
        'over-granulation',
        'under-granulation',
        '과과립',
        '미과립',
        'binder solution',
        'spray rate',
        'inlet air temperature',
        '결합액',
        '분무 속도',
        '유입 공기 온도',
    ],
    '고형제 - 타정': [
        'compression',
        'tablet press',
        'turret',
        'punch',
        'die',
        '타정',
        '타정기',
        '터렛',
        '펀치',
        '다이',
        'tablet weight variation',
        'hardness',
        'friability',
        '질량 편차',
        '경도',
        '마손도',
        'capping',
        'lamination',
        'sticing',
        'picking',
        '캡핑',
        '층분리',
        '부착',
        '점착',
        '스틱킹',
        '뜯김',
    ],
    '고형제 - 코팅': [
        'film coating',
        'enteric coating',
        'functional coating',
        '필름 코팅',
        '장용 코팅',
        '기능성 코팅',
        'coating uniformity',
        'weight gain',
        '코팅 균일성',
        '중량 증가율',
        'coating defects',
        'orange peel',
        'mottling',
        'cracking',
        'peeling',
        'picking',
        'twinning',
        '코팅 결함',
        '표면 거칠음',
        '얼룩',
        '균열',
        '박리',
        '코팅 뜯김',
        '정제 들러붙음',
        'solvent-based',
        'aqueous coating',
        '유기용매 코팅',
        '수계 코팅',
        'spray gun',
        'atomization',
        'pan speed',
        '스프레이 건',
        '분무 노즐',
        '미립화',
        '분무 미립화',
        '팬 속도',
    ],
    '교차 오염': [
        'cross contamination',
        'carryover',
        '교차 오염',
        '잔류 오염',
        'dust control',
        'dust explosion',
        'ATEX',
        '분진 관리',
        '분진 폭발',
        'cleaning validation',
        'MACO',
        'PED',
        'HBEL',
        '세척 밸리데이션',
        '허용 일일 노출량',
        '최대 허용 이월량',
        'shared equipment',
        'campaign production',
        '공유 설비',
        '캠페인 생산',
        'dedicated equipment',
        '전용 설비',
        '전용 생산 설비',
        'HVAC zoning',
        'pressure cascade',
        'differential pressure',
        '차압',
        '차압 구배',
    ],
}


def get_all_keywords():
    """?? ??? ??? ??"""
    all_kw = []
    for keywords in KEYWORDS.values():
        all_kw.extend(keywords)
    return list(set(all_kw))


def get_categories():
    """???? ?? ??"""
    return list(KEYWORDS.keys())


def classify_article(title: str, text: str = "") -> tuple[list, list]:
    """?? ??/???? ??? ?? ? ??? ?? ???? ??"""
    content = (title + " " + text).lower()
    matched_classifications = []
    matched_keywords = []

    for classification, keywords in KEYWORDS.items():
        for keyword in keywords:
            if keyword.lower() in content:
                if classification not in matched_classifications:
                    matched_classifications.append(classification)
                if keyword not in matched_keywords:
                    matched_keywords.append(keyword)

    return matched_classifications, matched_keywords


def get_gmp_categories():
    """GMP/QMS ?? ???? ??"""
    return list(KEYWORDS.keys())
